### PR TITLE
chore(release): 0.6.4

### PR DESCRIPTION
**Pull request by TarikGul**

### CODE REVIEW

**Comment by TarikGul** [comment]
When I run this release locally against sidecar i get this logging warning:

```
can't resolve reference #/definitions/directiveConfigSchema from id #
```

It can be ignored but I would like to get it resolved before we release

**Review by niklasad1 — APPROVED** [review]

**Comment by jsdw** [comment]
Interesting; it sounds like an openapi type thing offhand to me! I wonder whether `directiveConfigSchema` or similar appears anywhere in the node_modules stuff.

**Comment by TarikGul** [comment]
> Interesting; it sounds like an openapi type thing offhand to me! I wonder whether `directiveConfigSchema` or similar appears anywhere in the node_modules stuff.

I think youre correct about this. If I had to take an accurate guess it's probably with one of the 2 deps I updated.

**Review by lexnv — APPROVED** [review]

**Comment by TarikGul** [comment]
Okay this is good to release, ending up being a dedupe issue.

**Pull request merged**
